#!/usr/bin/env python3
"""Replay offline UART sensor captures into Firestore.

Consumes the upload queue generated by uart_sensor_offline_capture.py and writes
the captured sensor documents to Firebase with replayed received_at timestamps.
No UART device is used.

Supported input formats:
- sensor_upload_queue.jsonl: one Firestore-style operation per line.
- sensor_offline_export.json: grouped export with a top-level collections map.
"""

import argparse
import json
import os
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    from dotenv import load_dotenv
except ModuleNotFoundError:
    def load_dotenv():
        return False

try:
    from jsonschema import ValidationError, validate
except ModuleNotFoundError:
    ValidationError = None
    validate = None

load_dotenv()

FIREBASE_CREDENTIALS_PATH = os.getenv("FIREBASE_CREDENTIALS_PATH")
FIREBASE_COLLECTION = os.getenv("FIREBASE_COLLECTION", "iot-data")

DEFAULT_SCHEMA_PATH = (
    Path(__file__).resolve().parent
    / "Advanced-IoT-Mine-Safety-Monorepo"
    / "node-data-schema.json"
)
SCHEMA_PATH = Path(os.getenv("SCHEMA_PATH", str(DEFAULT_SCHEMA_PATH)))

DESKTOP_DIR = Path.home() / "Desktop"
DEFAULT_CAPTURE_DIR = (
    DESKTOP_DIR if DESKTOP_DIR.exists() else Path.home()
) / "uart_sensor_offline_capture"
DEFAULT_INPUT_FILE = Path(
    os.getenv("UART_OFFLINE_UPLOAD_FILE", str(DEFAULT_CAPTURE_DIR / "sensor_upload_queue.jsonl"))
)


def prompt_int(label: str, min_val: int, max_val: int) -> int:
    while True:
        raw = input(f"Enter {label}: ").strip()
        try:
            val = int(raw)
        except ValueError:
            print(f"  invalid: '{raw}' is not an integer")
            continue
        if not (min_val <= val <= max_val):
            print(f"  invalid: {val} outside [{min_val}, {max_val}]")
            continue
        return val


def prompt_float(label: str, min_val: float) -> float:
    while True:
        raw = input(f"Enter {label}: ").strip()
        try:
            val = float(raw)
        except ValueError:
            print(f"  invalid: '{raw}' is not a number")
            continue
        if val < min_val:
            print(f"  invalid: {val} is less than {min_val}")
            continue
        return val


def prompt_base_time() -> datetime:
    """Ask the user for a local date/time and return a tz-aware datetime."""
    local_tz = datetime.now().astimezone().tzinfo
    print(
        "Set the replay 'received_at' start time "
        f"(local: {local_tz}). Packet timestamps will be start + packet_index * wait_period."
    )
    while True:
        year = prompt_int("Year (yyyy)", 2000, 2100)
        month = prompt_int("Month (1-12)", 1, 12)
        day = prompt_int("Day (1-31)", 1, 31)
        hour = prompt_int("Hour (0-23)", 0, 23)
        minute = prompt_int("Minute (0-59)", 0, 59)
        second = prompt_int("Second (0-59)", 0, 59)
        try:
            base = datetime(year, month, day, hour, minute, second, tzinfo=local_tz)
            break
        except ValueError as e:
            print(f"  invalid date/time: {e} -- try again")
    print(
        f"[TIME] replay start = {base.strftime('%Y-%m-%d %H:%M:%S %Z')} "
        f"({base.astimezone(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')})"
    )
    return base


def prompt_wait_period() -> float:
    wait_period = prompt_float("Wait period between packets in seconds", 0.0)
    print(f"[TIME] wait period = {wait_period}s")
    return wait_period


def strip_proxy_env():
    for var in (
        "HTTP_PROXY",
        "HTTPS_PROXY",
        "ALL_PROXY",
        "http_proxy",
        "https_proxy",
        "all_proxy",
        "GRPC_PROXY",
        "grpc_proxy",
    ):
        os.environ.pop(var, None)
    print("[NET] proxy env vars stripped; gRPC/Firestore will connect directly.")


def load_schema(path: Path):
    if validate is None:
        print("[SCHEMA] jsonschema is not installed; validation disabled")
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            schema = json.load(f)
        print(f"[SCHEMA] loaded from {path}")
        return schema
    except Exception as e:
        print(f"[SCHEMA] not loaded from {path}: {e}")
        return None


def read_jsonl_queue(path: Path) -> list[dict]:
    packets = []
    with open(path, "r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as e:
                print(f"[INPUT] skipped invalid JSONL line {line_no}: {e}")
                continue

            if record.get("operation") != "firestore_add":
                print(f"[INPUT] skipped line {line_no}: unsupported operation {record.get('operation')!r}")
                continue

            document = record.get("document")
            if not isinstance(document, dict):
                print(f"[INPUT] skipped line {line_no}: missing object document")
                continue

            collection = record.get("collection") or FIREBASE_COLLECTION
            packets.append({"collection": collection, "document": document, "source": f"{path}:{line_no}"})
    return packets


def read_grouped_export(path: Path) -> list[dict]:
    with open(path, "r", encoding="utf-8") as f:
        export = json.load(f)

    collections = export.get("collections")
    if not isinstance(collections, dict):
        raise ValueError("grouped export must contain an object at top-level key 'collections'")

    packets = []
    for collection, documents in collections.items():
        if not isinstance(documents, list):
            print(f"[INPUT] skipped collection {collection!r}: value is not a list")
            continue
        for index, document in enumerate(documents, start=1):
            if not isinstance(document, dict):
                print(f"[INPUT] skipped {collection}[{index}]: document is not an object")
                continue
            packets.append({
                "collection": collection or FIREBASE_COLLECTION,
                "document": document,
                "source": f"{path}:{collection}[{index}]",
            })
    return packets


def load_packets(path: Path) -> list[dict]:
    if not path.is_file():
        raise FileNotFoundError(f"input file not found: {path}")

    if path.suffix.lower() == ".jsonl":
        packets = read_jsonl_queue(path)
    else:
        packets = read_grouped_export(path)

    if not packets:
        raise ValueError(f"no uploadable packets found in {path}")
    print(f"[INPUT] loaded {len(packets)} packet(s) from {path}")
    return packets


def replay_document(document: dict, received_at: datetime) -> dict:
    replayed = normalize_sensor_document(document)
    replayed.pop("offline_captured", None)
    replayed.pop("offline_queued", None)
    replayed["received_at"] = received_at
    replayed["received_by"] = replayed.get("received_by") or "pi-basestation"
    replayed["replayed_from_offline_capture"] = True
    return replayed


def _default_if_missing_or_null(container: dict, key: str, default_value):
    if container.get(key) is None:
        container[key] = default_value


def _numeric_default(container: dict, key: str, default_value=0):
    value = container.get(key)
    if value is None or not isinstance(value, (int, float)):
        container[key] = default_value


def _vector_default(value) -> dict:
    if not isinstance(value, dict):
        value = {}
    for axis in ("x", "y", "z"):
        _numeric_default(value, axis, 0)
    return value


def normalize_sensor_document(document: dict) -> dict:
    """Fill required schema fields when offline captures have missing/null values."""
    normalized = dict(document)

    _default_if_missing_or_null(normalized, "node_id", "00:00:00:00:00:00")
    _default_if_missing_or_null(normalized, "led_state", "#000000")

    transmission_attempts = normalized.get("transmission_attempts")
    if transmission_attempts is None or not isinstance(transmission_attempts, int):
        normalized["transmission_attempts"] = 0

    env = normalized.get("environment")
    if not isinstance(env, dict):
        env = {}
    else:
        env = dict(env)

    _numeric_default(env, "temperature", 0)
    _numeric_default(env, "humidity", 0)
    _numeric_default(env, "barometric_pressure", 0)
    env["accelerometer"] = _vector_default(env.get("accelerometer"))
    env["gyroscope"] = _vector_default(env.get("gyroscope"))
    normalized["environment"] = env

    return normalized


def validation_payload(document: dict) -> dict:
    payload = normalize_sensor_document(document)
    for key in (
        "received_at",
        "received_by",
        "offline_captured",
        "offline_queued",
        "replayed_from_offline_capture",
    ):
        payload.pop(key, None)
    return payload


def init_firestore():
    try:
        import firebase_admin
        from firebase_admin import credentials, firestore
    except ModuleNotFoundError as e:
        missing = e.name or "firebase-admin"
        print(f"Missing dependency: {missing}. Install dependencies with: pip install firebase-admin")
        return None, None

    if not FIREBASE_CREDENTIALS_PATH:
        raise ValueError("FIREBASE_CREDENTIALS_PATH environment variable is required")

    cred_path = Path(FIREBASE_CREDENTIALS_PATH)
    if not cred_path.is_absolute():
        cred_path = (Path(__file__).resolve().parent / cred_path).resolve()
    if not cred_path.is_file():
        raise FileNotFoundError(f"service account file not found: {cred_path}")

    print(f"[FIREBASE] using credentials: {cred_path}")
    if not firebase_admin._apps:
        cred = credentials.Certificate(str(cred_path))
        firebase_admin.initialize_app(cred)

    db = firestore.client()
    print("[FIREBASE] initialized")
    return db, firestore


def test_firestore_connection(db, firestore):
    ping_ref = db.collection(FIREBASE_COLLECTION).document("_replay_connection_test")
    ping_ref.set({
        "ping": True,
        "tested_at": firestore.SERVER_TIMESTAMP,
        "tested_by": "firebase_replay_offline_capture.py",
    })
    ping_ref.delete()
    print(f"[FIREBASE] [OK] Firestore reachable (write+delete to {FIREBASE_COLLECTION}/_replay_connection_test)")


def packet_summary(document: dict) -> str:
    node_id = document.get("node_id", "?")
    env = document.get("environment", {}) or {}
    parts = [f"node={node_id}"]
    if isinstance(env.get("temperature"), (int, float)):
        parts.append(f"temp={env['temperature']:.1f}C")
    if isinstance(env.get("humidity"), (int, float)):
        parts.append(f"hum={env['humidity']:.1f}%")
    if isinstance(env.get("barometric_pressure"), (int, float)):
        parts.append(f"p={env['barometric_pressure']:.1f}hPa")
    if isinstance(document.get("battery_voltage"), (int, float)):
        parts.append(f"batt={document['battery_voltage']:.2f}V")
    if "transmission_attempts" in document:
        parts.append(f"tx={document['transmission_attempts']}")
    return "  ".join(parts)


def main():
    parser = argparse.ArgumentParser(
        description="Replay an offline UART sensor capture file into Firebase."
    )
    parser.add_argument(
        "input_file",
        nargs="?",
        type=Path,
        default=DEFAULT_INPUT_FILE,
        help=f"offline queue/export file (default: {DEFAULT_INPUT_FILE})",
    )
    parser.add_argument(
        "--collection",
        default=None,
        help="override the Firestore collection for every packet",
    )
    parser.add_argument(
        "--no-schema",
        action="store_true",
        help="upload packets without validating against node-data-schema.json",
    )
    parser.add_argument(
        "--no-proxy",
        action="store_true",
        help="Strip HTTP(S)_PROXY/ALL_PROXY from env before Firebase init. "
             "Needed when the network proxy blocks gRPC.",
    )
    args = parser.parse_args()

    if args.no_proxy:
        strip_proxy_env()

    replay_start = prompt_base_time()
    wait_period = prompt_wait_period()

    packets = load_packets(args.input_file)
    schema = None if args.no_schema else load_schema(SCHEMA_PATH)

    try:
        db, firestore = init_firestore()
        if db is None:
            return
        test_firestore_connection(db, firestore)
    except Exception as e:
        print(f"[FIREBASE] init/test failed: {e}")
        return

    uploaded = 0
    skipped = 0
    failed = 0

    try:
        for index, packet in enumerate(packets):
            collection = args.collection or packet["collection"]
            source_doc = packet["document"]

            if schema is not None:
                try:
                    validate(instance=validation_payload(source_doc), schema=schema)
                except ValidationError as e:
                    skipped += 1
                    print(f"[{index + 1}/{len(packets)}] skipped schema-invalid packet: {e.message}")
                    continue

            received_at = replay_start + timedelta(seconds=index * wait_period)
            upload_doc = replay_document(source_doc, received_at)

            try:
                doc_ref = db.collection(collection).add(upload_doc)
                uploaded += 1
                timestamp = received_at.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
                print(
                    f"[{index + 1}/{len(packets)}] Firestore OK: {collection}/{doc_ref[1].id} "
                    f"received_at={timestamp}  {packet_summary(source_doc)}"
                )
            except Exception as e:
                failed += 1
                print(f"[{index + 1}/{len(packets)}] Firestore write FAILED ({packet['source']}): {e}")

            if index < len(packets) - 1 and wait_period > 0:
                time.sleep(wait_period)
    except KeyboardInterrupt:
        print("\nReplay interrupted.")

    print(f"[DONE] uploaded={uploaded} skipped={skipped} failed={failed} total={len(packets)}")


if __name__ == "__main__":
    main()
